language: go

go:
  - 1.2
  - 1.3

before_install:
    - go get github.com/mattn/gom

matrix:
  allow_failures:
    - go: 1.3
  fast_finish: true

services:
  - rabbitmq
  - redis-server

script: make

notifications:
  email: false
